### ISSUE TITLE
[feature]: Integrated with NX

### ISSUE THREAD

**Issue by kamontat** [kamontat/kcutils#341]
# Feature request

NX offer several feature to improve development process that we use take a look. Although, it also lack of feature that we currently use in lerna (such as automatic run deployment flow)

## Is your feature request related to a problem?

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## Describe the solution you'd like

> A clear and concise description of what you want to happen.

## Additional context

> Add any other context or screenshots about the feature request here.

**Comment by kamontat** [comment]
I working on POC on PR #357, stay tune :)

**Comment by kamontat** [comment]
# Tasks

- [ ] Replace all build scripts in command.sh to use nx workspace instead of lerna
- [ ] Update CI to use new nx workspace (and nx cloud bot) to optimize task execution
- [ ] Change lerna to deployment platform instead
- [ ] Explorer nx generator and executor with current project layout
- [ ] Add nx dependencies graph to kcutils website
